h100:
- 'h100-cw_00'
- 'h100-cw_01'
- 'h100-dgxc-slurm_00'
- 'h100-dgxc-slurm_01'
- 'h100-dgxc-slurm_02'
- 'h100-dgxc-slurm_03'
- 'h100-dgxc-slurm_04'
- 'h100-dgxc-slurm_05'
- 'h100-dgxc-slurm_06'
- 'h100-dgxc-slurm_07'
- 'h100-dgxc-slurm_08'
- 'h100-dgxc-slurm_09'
- 'h100-dgxc-slurm_10'
- 'h100-dgxc-slurm_11'
- 'h100-dgxc-slurm_12'
- 'h100-dgxc-slurm_13'
- 'h100-dgxc-slurm_14'
- 'h100-dgxc-slurm_15'
- 'h100-dgxc-slurm_16'
- 'h100-dgxc-slurm_17'
- 'h100-dgxc-slurm_18'
- 'h100-dgxc-slurm_19'
h100-multinode:
- 'h100-dgxc-slurm_16'
- 'h100-dgxc-slurm_17'
- 'h100-dgxc-slurm_18'
- 'h100-dgxc-slurm_19'
h200:
- 'h200-cw_00'
- 'h200-cw_01'
- 'h200-nb_0'
- 'h200-nb_1'
- 'h200-dgxc-slurm_0'
- 'h200-dgxc-slurm_1'
- 'h200-dgxc-slurm_2'
- 'h200-dgxc-slurm_3'
- 'h200-dgxc-slurm_4'
- 'h200-dgxc-slurm_5'
- 'h200-dgxc-slurm_6'
- 'h200-dgxc-slurm_7'
- 'h200-dgxc-slurm_8'
- 'h200-dgxc-slurm_9'
- 'h200-dgxc-slurm_10'
- 'h200-dgxc-slurm_11'
- 'h200-dgxc-slurm_12'
- 'h200-dgxc-slurm_13'
h200-multinode:
- 'h200-dgxc-slurm_11'
- 'h200-dgxc-slurm_12'
- 'h200-dgxc-slurm_13'
h200-dgxc:
- 'h200-dgxc-slurm_0'
- 'h200-dgxc-slurm_1'
- 'h200-dgxc-slurm_2'
- 'h200-dgxc-slurm_3'
- 'h200-dgxc-slurm_4'
- 'h200-dgxc-slurm_5'
- 'h200-dgxc-slurm_6'
- 'h200-dgxc-slurm_7'
- 'h200-dgxc-slurm_8'
- 'h200-dgxc-slurm_9'
- 'h200-dgxc-slurm_10'
- 'h200-dgxc-slurm_11'
- 'h200-dgxc-slurm_12'
- 'h200-dgxc-slurm_13'
b200:
- 'b200-cw_00'
- 'b200-cw_01'
- 'b200-nb_0'
- 'b200-nb_1'
- 'b200-dgxc_00'
- 'b200-dgxc_01'
- 'b200-dgxc_02'
- 'b200-dgxc_03'
- 'b200-dgxc_04'
- 'b200-dgxc_05'
- 'b200-dgxc_06'
- 'b200-dgxc_07'
- 'b200-dgxc_08'
- 'b200-dgxc_09'
- 'b200-dgxc_10'
- 'b200-dgxc_11'
- 'b200-dgxc_12'
- 'b200-dgxc_13'
- 'b200-dgxc_14'
- 'b200-dgxc_15'
- 'b200-dgxc_16'
b200-multinode:
- 'b200-dgxc-slurm_6'
- 'b200-dgxc-slurm_7'
- 'b200-dgxc-slurm_8'
mi300x:
- 'mi300x-amds_00'
- 'mi300x-amds_01'
- 'mi300x-amds_02'
- 'mi300x-amds_03'
- 'mi300x-amds_04'
- 'mi300x-amds_05'
- 'mi300x-amds_06'
- 'mi300x-amds_07'
- 'mi300x-amds_08'
mi300x-disagg:
- 'mi300x-amds_06'
- 'mi300x-amds_07'
- 'mi300x-amds_08'
mi325x:
- 'mi325x-amds_00'
- 'mi325x-amds_01'
- 'mi325x-amds_02'
- 'mi325x-amds_03'
- 'mi325x-amds_04'
- 'mi325x-amds_05'
- 'mi325x-amds_06'
- 'mi325x-amds_07'
- 'mi325x-amds_08'
mi325x-disagg:
- 'mi325x-amds_00'
- 'mi325x-amds_01'
- 'mi325x-amds_02'
- 'mi325x-amds_03'
- 'mi325x-amds_06'
- 'mi325x-amds_07'
- 'mi325x-amds_08'
mi355x:
- 'mi355x-amds_0'
- 'mi355x-amds_1'
- 'mi355x-amds_2'
- 'mi355x-amds_3'
- 'mi355x-amds_4'
- 'mi355x-amds_5'
- 'mi355x-amds_6'
- 'mi355x-amds_7'
- 'mi355x-amds_8'
mi355x-disagg:
- 'mi355x-amds_6'
- 'mi355x-amds_7'
- 'mi355x-amds_8'
gb200:
- gb200-nv_0
- gb200-nv_1
- gb200-nv_2
b300:
- 'b300-nv_0'
- 'b300-nv_1'
- 'b300-nv_2'
- 'b300-nv_3'
- 'b300-nv_4'
- 'b300-nv_5'
- 'b300-nv_6'
- 'b300-nv_7'
- 'b300-nv_8'
gb300:
- 'gb300-nv_0'
- 'gb300-nv_1'
- 'gb300-nv_2'
gb300-cw:
- 'gb300-cw_0'
- 'gb300-cw_1'
- 'gb300-cw_2'
- 'gb300-cw_3'
